spring:
  application:
    name: jsonapi4j-springboot-sampleapp

server:
  port: 8080

integrations:
  rest-countries:
    url: https://restcountries.com/v3.1

jsonapi4j:
  root-path: '/jsonapi'
  compound-docs:
    enabled: true
    maxHops: 3
    mapping:
      users: http://localhost:${server.port}${jsonapi4j.root-path}
      countries: http://localhost:${server.port}${jsonapi4j.root-path}
      currencies: http://localhost:${server.port}${jsonapi4j.root-path}
  oas:
    enabled: true
    info:
      title: 'JSON:API Users & Countries'
      version: 1.0.0
    oauth2:
      client-credentials:
        name: 'Client_Credentials'
        description: 'Use this grant flow to access non-personalized data.'
        scopes: { }
    servers:
      server-local:
        name: Localhost
        enabled: true
        url: http://localhost:${server.port}
      server-staging:
        name: Staging
        url: 'https://api.stage.com'
      server-prod:
        name: Production
        url: 'https://api.com'

logging:
  level:
    root: INFO