remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
description: Lightweight API framework for Java for building JSON:API-compliant APIs with minimal configuration
show_downloads: false